### ISSUE TITLE
Docker pull only if required

### ISSUE THREAD

**Issue by sdaschner** [appsody/appsody#114]
**Is your feature request related to a problem? Please describe.**
Running `appsody run` (and others) always attempts to do a `docker pull` for the used platform image (e.g. `java-microprofile`). This always takes a moment to connect, check, or fail on a missing (locally-built) image. It would improve the developer experience if that step would be removed, since it simply takes too long (adds an additional second or so, depending on the network connection) and adds an unnecessary network step.

**Describe the solution you'd like**
Only docker pull's for when it's necessary.

**Comment by chilanti** [comment]
@sdaschner - you can set the "semi-secret" env var *APPSODY_PULL_POLICY* (prior to invoking appsody) to _IfNotPresent_ and we won't pull every time. I think we didn't document it this "feature" yet - but it should work... please let us know (and as you may be aware, remember there are some implications: if the image changes "in place" on Dockerhub because of some emergency fix, you wouldn't get the updates).

**Comment by sdaschner** [comment]
Awesome, works, thanks! Opened an issue to document it
