### ISSUE TITLE
appsody init doesn't show docker pull progress

### ISSUE THREAD

**Issue by sdaschner** [appsody/appsody#115]
**Is your feature request related to a problem? Please describe.**
The docker pull that is performed on `appsody init` doesn't show the progress of the image pull. This gives developers no feedback on the remaining time of the initialization.

**Describe the solution you'd like**
Displaying a progress similar to a usual `docker pull`.

**Comment by neeraj-laad** [comment]
@sdaschner Thanks for raising this issue. By default we are not showing the logs from the docker commands that appsody runs.. These are visible if you use the `-v` option on the cli commands.

The reason was to limit the amount of logs the user sees but the side effect is that there are certain points where user sees no feedback. This is also very notable during appsody build. 

We will think of a better way of providing some feedback to the user.

@appsody/cli

**Comment by sdaschner** [comment]
Sounds good. E.g. there are ways to display a progress bar that "disappears" again, i.e. the output is not appended to the console but "replaced" once the pull is done. I think that would be a good solution.

If folks have a slow connection the output "freezes" for an indefinite amount of time otherwise.

**Comment by kylegc** [comment]
I've heard this same feedback from multiple people.
I agree with Sebastian, we should do something to improve this.
