### ISSUE TITLE
Clean extract folder after appsody build

### ISSUE THREAD

**Issue by sdaschner** [appsody/appsody#120]
What was the motivation of having the exported applications under `~/.appsody/extract/` and not directly under the project directory?

IMO this has the following disadvantages:
- Harder to find / access or to comprehend.
- Layout would be more concise to have it at the same place
- Unnecessary collisions for projects with the same name.
- Bigger risk of growing unnecessarily large, being ignored, or forgotten.

I think there is a difference between storing external dependencies, such as everything resolved via Maven (`~/.m2/`, which makes sense) and output produced by a project, similar to `build/`, `target/`, `out/`, and others.

**Proposal**

Changing the extracted location to `.appsody/` under the project (current) directory. Easy to find, easy to exclude from Git and others, and easy to spot and clean-up.

As a first step, we could ensure that `appsody build` cleans up the extracted folder so there is nothing leftover for the next run or another project.

## Summary

**Comment by chilanti** [comment]
@kylegc and I had a lot of discussions on this. We decided to avoid polluting the project directory, because that's the directory where the developers' source code exists.
We figured, based on our experience as developers, that some would be finding it annoying and confusing if appsody - all of a sudden - created a "sister" extract folder under the project dir with pretty much the same contents as the "real" project dir (also: we would have to ensure that the watcher is disabled for the extract directory, or appsody would think that those are legit changes that need to be injected in the runtime).
But we agree that things like collisions, obscurity, and hygiene are an issue - thanks for raising those.

**Comment by sdaschner** [comment]
I see, valid points.

How about making sure that the `build` commands cleans the extracted directory again after it has been executed successfully? That would somewhat limit the clutter.

**Comment by ebullient** [comment]
I am with Sebastian. I would rather the extract stayed in the source project, too. 

An `.appsody` directory in the project could have CLI managed ignore rules (and could always be excluded from watch).

**Comment by kylegc** [comment]
Besides the points Michele brought up above, extracting into the project dir would introduce a recursive copy problem. You would be copying files into the same directory (or docker mount point) which you are copying from.

In order to avoid the recursive copy problem, you'd have to extract to a folder outside the project anyway, then at the end move it back into the project. This is exactly what we do with the `--target-dir` option.

**Comment by sdaschner** [comment]
As @ebullient wrote, we can simply ignore such a directory. Basically "list all files and directories in the current one *except* `.appsody` (or else), and then copy them to `.appsody/extract`". I don't see a recursive copy problem here, if we construct the commands a little bit more cleverly.

**Comment by kylegc** [comment]
You are oversimplifying it. We run a `docker cp` command to actually copy the mounted files out of a container to the local file system. I'm not saying it is impossible to ignore a directory, but it is harder than you think. We can keep this item open on the backlog, but it is low priority for now.

**Comment by neeraj-laad** [comment]
@kylegc I'm trying to figure out if we are aware of the `build` command not properly cleaning up the extracted directory? 

If that is not the case, we can at least implement that bit easily

**Comment by kylegc** [comment]
Thanks for pointing this out Neeraj. No I hadn't considered cleaning up/removing the `~/.appsody/extract` dir after a `build`.

Lets use this issue to implement that.
