### ISSUE TITLE
Validate Dockerfile-stack in Linter

### ISSUE THREAD

**Issue by Kamran64** [appsody/appsody#270]
**Is your feature request related to a problem? Please describe.**
Currently the stacks linter will only verify that a Dockerfile-stack exists, but won't actually validate the contents of the file. As a result the lint test will pass even if the file is empty. 

The linter could validate the use of environment variables within the Dockerfile-stack and ensure e.g. directories set for WATCH_DIR exist.

If we could post rules that a Dockerfile-stack must conform to either here or in the [linter epic](https://github.com/appsody/stacks/issues/199)

**Comment by Bazif-Khan** [comment]
These environment variables should be present:

**Error:**
- [ ] APPSODY_MOUNTS
- [ ] APPSODY_RUN
- [ ] APPSODY_RUN_ON_CHANGE
- [ ] APPSODY_RUN_KILL
- [ ] APPSODY_DEBUG
- [ ] APPSODY_DEBUG_ON_CHANGE
- [ ] APPSODY_DEBUG_KILL
- [ ] APPSODY_TEST
- [ ] APPSODY_TEST_ON_CHANGE
- [ ] APPSODY_TEST_KILL

These environment variables are optional:

**Warning:**
- [ ] APPSODY_DEPS
- [ ] APPSODY_WATCH_DIR

**Comment by neeraj-laad** [comment]
@Bazif-Khan I believe we need some changes on this:

**What vars are allowed and when:**
- *ON_CHANGE: should be optional
- *_KILL: should be optional
- IF WATCH_DIR is preset we expect to have at least one ON_CHANGE
- IF WATCH_DIR is not preset we expect to not have any ON_CHANGE
- APPSODY_INSTALL should be deprecated and APPSODY_PREP should be used instead.

What values are allowed and when:
* *KILL should be trtue/false
* APPSODY_WATCH_REGEX - check value is a valid regex
* Validation on paths?
* APPSODY_PROJECT_DIR should be used?

**Comment by kewegner** [comment]
Re: IF WATCH_DIR is present we expect to have at least one ON_CHANGE
Currently if there is no WATCH_DIR we default to the mount dirs if there is an ON_CHANGE setting.
I think what we should do is print an info message that if WATCH_DIR is not present and an ON_CHANGE is that we default to the MOUNTS_DIR

Re the regex. 

Given that true validation is kind of dependent on what is the source being watched, (e.g. what text we run the regex on..) I am not sure how deep a validation one could do.

The one thing we do not allow is "Currently negative look ahead matching (e.g. ignore patterns) is not supported".  Due to the regex package the watcher from radofsky uses, doesn't support that.
That is the reason we have the WATCH IGNORE directories.

This might be helpful https://www.regular-expressions.info/refadv.html as a reference. 

I wonder if just doing a compile on the regex is a good first step?  That would be my recommendation.

I fear trying to do anything with the negative look ahead checking might accidentally flag a valid regex.
