### ISSUE TITLE
Revise logging strategy for CLI unit tests

### ISSUE THREAD

**Issue by kilnerm** [appsody/appsody#493]
Currently the CLI unit tests output a huge volume of text which can make it hard to find where failures are occurring. 

We should look at how we can best capture and organize the test output to make it more consumable.

**Comment by kylegc** [comment]
See PR https://github.com/appsody/appsody/pull/566 for what I already had for this.

**Comment by djones6** [comment]
I've been working through various ideas on how to better control the test output.  Here's what I have tried so far:

- Changing all use of `fmt.Print` to `t.Log`: this causes go to buffer all of the output until the test completes.  However, it's _always_ printed in `-v` mode.  If you don't run with verbose, then it is only printed if a test fails, but unfortunately, go does not print any output at all for passing tests.  This is confusing and will likely cause CI to time out.
- Rather than logging appsody commands to `t.Log`, only return the output in a buffer that the tests inspect.  Tests individually choose to log this buffer (or not), for example, if they detect an error condition.
- Rather than redirecting stdout and stderr around appsody calls, allow appsody's output/error writers to be configurable, and configure them to write to a buffer rather than stdout/stderr.  This simplifies the test code.  However, it doesn't work any better for cases where we run multiple commands in different threads (since stdout/stderr and appsody's logging configuration are globals).  For example, the TestBuildSimple functional test runs `appsody build` in a separate thread, and this output ends up on stdout.
- Running all commands through exec would solve the output handling problem, but this is unappealing as it would prevent debugging of those commands within tests.

### Redesigning logging

One option I'm considering is to change the way that the CLI's logging is handled. At the moment, logging is configured globally, so it is not possible to run multiple commands concurrently with different logging destinations.

By moving the log configuration onto a type, we could customize the configuration for each command independently.  Because the CLI uses cobra, that type would need to be an extension on Cobra's command type.  The log destination and functions would then be defined on this type, and we'd need to replace calls eg: `Error.Log(error)` with something like `cmd.logError(error)`.

**Comment by djones6** [comment]
Work-in-progress for making logging configuration per-command rather than global: https://github.com/djones6/appsody/tree/logOutput

**Comment by kylegc** [comment]
This was completed by several PRs:
#566
#639 
#657
