### ISSUE TITLE
appsody repo list -o json doesn't only return JSON when update is available

### ISSUE THREAD

**Issue by james-wallis** [appsody/appsody#563]
**Describe the bug**
Running `appsody repo list -o json` doesn't just output JSON.

**To Reproduce**
1. Using an old version of Appsody (I'm using `0.4.7`) run the command `appsody repo list -o json`.

**Expected behavior**
Only JSON output as the flag `-o json` has been added.
```
{"apiVersion":"v1","generated":"2019-11-01T14:07:46.0016815Z","repositories":[{"name":"appsodyhub","url":"https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml","default":true},{"name":"experimental","url":"https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml"}]}
```

**Actual behaviour**
What is the actual behaviour.
An update message as well as the JSON
```
*
*
*

A new CLI update is available.
Please go to https://appsody.dev/docs/getting-started/installation#upgrading-appsody and upgrade from 0.4.7 --> 0.4.8.

*
*
*

{"apiVersion":"v1","generated":"2019-11-01T11:56:18.6478923Z","repositories":[{"name":"appsodyhub","url":"https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml","default":true},{"name":"experimental","url":"https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml"}]}
```

When Appsody cannot check the most recent version in Github it will print:
```
[Warning] Unable to check the most recent version of Appsody in GitHub.... continuing.

{"apiVersion":"v1","generated":"2019-11-01T14:07:46.0016815Z","repositories":[{"name":"appsodyhub","url":"https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml","default":true},{"name":"experimental","url":"https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml"}]}`
```

If you're running the Appsody command and then parsing it as JSON the command will break whenever Appsody does an update.

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Terminal

**If applicable please specify:**
 - CLI version: 0.4.7
 - Stack you are using: N/A

**Comment by kylegc** [comment]
First, we should make the "new CLI update is available" text a Warning, that way it gets printed to stderr instead of stdout. We can't ensure there will be no Warnings or Errors in other parts of the code. Since these get printed to stderr, the json parser should only read stdout.

Second, I think it is valid to provide a way to skip the new version check. A couple ways we could do that:
- Provide a global command line flag
- Provide a `~/.appsody/.appsody.yaml` attribute to set

**Comment by kylegc** [comment]
@chilanti @neeraj-laad which approach do you like? I think we should do the Warning/stderr for sure, but what about the second way to fully skip the version check?

I tend to lean away from a global command line flag. Not necessarily because of too many flags, but because I don't think it will be used by users very often and we don't want to encourage users to use it. This makes most sense for scripts or tools using appsody, and they should be able to set an environment variable or property in a file.

**Comment by james-wallis** [comment]
+1 I think either an environment variable or property in the config file would be best (in addition to the Warning/stderr which I am happy to raise as a PR). 

Would there be a case to add functionality to allow users to set it both by environment variable and the property in the file? In a file would be great for users who want it set all the time and an env would work in scripts without having to worry about setting a config file?

**Comment by neeraj-laad** [comment]
Yes, we should definitely change that message to a warning. @james-wallis look fwd to a PR.

Regarding the other change, I like it to be an attribute in `.appsody.yaml` and I believe we already have an issue to provide the ability to set these values using cli command.

**Comment by ianpartridge** [comment]
Why wouldn't we omit the warning message when `-o json` is specified? If someone is passing that option they obviously want output that can be consumed programatically. In fact, it's likely that they're driving the CLI itself programmatically which might make having to set something in `.appsody.yaml` to get valid JSON output awkward.

**Comment by kylegc** [comment]
@ianpartridge, I'm not entirely opposed to skipping the version check when `-o json` is specified, but my point above is that other code may spit out other warning messages. It would be very difficult to go through all possible code paths and suppress warnings for the `-o` case. Plus I don't think we should do this, warnings are there for a reason.

I agree that with `-o json`, the CLI will likely be driven programmatically. Therefore separating stdout (the json) from stderr (the warnings) should not be a problem.

I also agree that setting something in `.appsody.yaml` is awkward, which is why I also suggested an environment variable. That should be easy and normal practice to set programmatically.

**Comment by ianpartridge** [comment]
Personally I think the version check output is a bit obnoxious and I can't think of other CLIs (`kubectl`, `helm`, `docker` etc.) which do the same thing to notify users that an update is available.  But I understand the Appsody CLI is evolving fast at the moment so there's value in pushing users to upgrade proactively.  Longer-term I think the upgrade warning should be opt-in.

> It would be very difficult to go through all possible code paths and suppress warnings for the -o case. Plus I don't think we should do this, warnings are there for a reason.

Are you saying it's possible that the JSON output could be invalid, because the user is running an old version of the CLI?

**Comment by kylegc** [comment]
Personally I think the version check output should be a one-line warning...

I'm saying that stdout will contain valid JSON, and stderr _may_ contain warning messages. Through a console these _may_ get intermingled even though we will try to avoid intermingling.

**Comment by ianpartridge** [comment]
Thanks, I understand.. I was exploring "warnings are there for a reason". What's the reason the `-o json` output needs to warn if the CLI is out of date? I would have thought the only good reason to warn in that case would be if there was a potential the JSON might be invalid, but it doesn't sound like that's the case?

**Comment by kylegc** [comment]
> What's the reason the -o json output needs to warn if the CLI is out of date?

To let the user or script maintainer know (or remind them) that they are using an old version of appsody. Again, I'm not entirely opposed to skip this warning with `-o json`, but if the reason for skipping the warning is to parse the combined stdout and stderr to json, I say that is still not safe because there may be other warnings on stderr.

Examples of other such warnings include if a default repository is not set, one of the repositories is unreachable, an invalid repository.yaml or index.yaml, etc. These cases should still produce valid (parsable) json, but the information may be incomplete.

**Comment by makandre** [comment]
Kind of late to the conversation, but my vote is for splitting stdout/stderr **and** skipping version check when `-o` is used.

**Comment by james-wallis** [comment]
In case anyone missed, the PR to move the update warning was accepted a few days ago. (Commenting as I can't link the issue). 
[Appsody PR #603](https://github.com/appsody/appsody/pull/603)

**Comment by kylegc** [comment]
Yep Thanks James. #603 takes care of the first part of this issue.
We left this issue open to take care of the second part:
Provide two methods to skip the version check:
- An `~/.appsody/.appsody.yaml` attribute (or value on the existing timestamp attribute)
- An environment variable
