### ISSUE TITLE
appsody completion could support zsh

### ISSUE THREAD

**Issue by sam-github** [appsody/appsody#645]
**Is your feature request related to a problem? Please describe.**

kubectl, helm, and minikube completion commands all support zsh, appsody does not.

**Describe the solution you'd like**

To support `appsody completion zsh`

**Describe alternatives you've considered**

Not using completion?

**Additional context**

I ran into this on Linux, where I chose zsh, but this will become a problem for mac users very soon, if not already: https://scriptingosx.com/2019/06/moving-to-zsh/

```
source <(helm completion zsh)
source <(kubectl completion zsh)
source <(minikube completion zsh)
#source <(appsody completion zsh) # :-(
```

It would also be useful if `appsody completion` errored when given invalid arguments, rather than ignoring them.

**Comment by kewegner** [comment]
Thanks for the input.
This is something we could relatively easily I think.

**Comment by kewegner** [comment]
Investigation:
I did some testing with appsody completion.

There is a cobra command function _Cmd.GenZshCompletion(buf) which will generate the completions, which combined with some argument checking (appsody completion bash/zsh) will generate the completions if used in our completion.go.

However, the big drawback is that we are currently on spf13 cobra 0.0.3 and flags are not supported for zsh completions.

I temporarily updated my appsody project to spf13 cobra 0.0.5 and the flags are now covered by the completions.  And I was able to generate a  zsh completion file I could use.

I would also add that it provides help text for the flag options, which is something the cobra bash completion support does not give you, even in 0.0.5.

We would have to consider the risk of updating to 0.0.5 to get the flag functionality just for zsh, as the update would impact the entire Appsody CLI.   We could choose to initially release completion support for zsh that didn't cover the flags, but that would not be as useful obviously.

It also appears that if you upgraded your Mac to Catalina, atm at least, it doesn't force zsh on you, it's still bash.  There is a simple update process to go to zsh (and back to bash if you choose). So the zsh terminal concern is more for a brand new install on Mac or a for user who is partial to zsh.

Finally in terms of implementation, I would not recommend we write any custom script for appsody init completion as we did for bash to list the stacks, since even in bash that is limited and we can not e show the templates for the stacks.


Set up Notes:
1.  You need to change your shell to zsh
https://support.apple.com/en-us/HT208050

2. The _appsody script must be puth in a directory in the fpath
I used ~/zshcomp

3. You need a .zshrc file
With these lines

# COMPLETION SETTINGS
# add custom completion scripts
fpath=(~/zshcomp $fpath)

# compsys initialization
autoload -U compinit
compinit

4. I upgraded my appsody project to spf13/cobra 0.0.5 using:

dep ensure -update github.con/spf13/cobra

**Comment by sam-github** [comment]
Thanks for looking at this.

I'd hope cobra 0.0.5 was backwards compat with 0.0.3, but maybe they weren't careful.

For anyone experimenting, you probably don't need to change your login shell, you can just run zsh:
```bash
bash %  zsh
zsh % source <(appsody completion zsh)
```

Or even:
```
bash %  appsody completion zsh > _init
bash % zsh _init
_init:type:1097: bad option: -t
_init:1100: command not found: complete
```
