### ISSUE TITLE
Operator fails install to a specified namespace when query of all-namespaces is restricted

### ISSUE THREAD

**Issue by leochr** [appsody/appsody#813]
@richard-trotter commented on [Mon Dec 16 2019](https://github.com/appsody/appsody-operator/issues/201)

## Bug Report

I recently received notice of some RHOCP enablement resources, including a course on OpenShift 4. The course includes labs that use a provided RHOCP shared cluster. Since IBM Public Cloud does not provide an OpenShift Lite (free) option, this cluster seemed like a good place to evaluate deployment of an AppsodyApplication to an OpenShift cluster. Of course this requires installation of the Appsody Operator. 

I can only install resources to my own namespace, and installation of Appsody to my own namespace fails.

It looks like this is failing while trying to determine if the operator is already installed, and is failing because 'get pods' is run with '-all-namespaces' but I don't have auth (in this shared cluster) to query all namespaces.  Seems like a bug, that '-all-namespaces'  is used instead of '--namespace eda4-appsody-deployment '.
$ appsody operator install --namespace eda4-appsody-deployment --verbose
...
[Debug] watchNamespace is:  eda4-appsody-deployment
[Info] Running command: kubectl get deployments -o=jsonpath='{.items[?(@.metadata.name=="appsody-operator")].metadata.namespace}' -n eda4-appsody-deployment
[Info] There are no deployments with appsody-operator
[Debug] Looking for an operator matching watchspace: eda4-appsody-deployment
[Info] Running command: kubectl get pods -o=jsonpath='{.items[?(@.metadata.labels.name=="appsody-operator")].metadata.namespace}' --all-namespaces
[Error] kubectl command failed: ''

### Environment

* Appsody CLI version: 0.5.3

* Appsody Stack: java-spring-boot2

* Kubernetes version information: 
$ oc version --short
Client Version: v4.0.22
Server Version: v1.13.4+28c3de7

---

@arturdzm commented on [Mon Dec 16 2019](https://github.com/appsody/appsody-operator/issues/201#issuecomment-566174662)

The installation code you referring to is in Appsody CLI
https://github.com/appsody/appsody

**Comment by chilanti** [comment]
This is a valid issue. Appsody tries to do "the right thing" by preventing the installation of redundant operators that concurrently watch the same namespace, but in order to do so, it requires the ability of detecting (i.e. querying) operators all around the cluster. In most shared cluster environments, this isn't viable, because of RBAC constraints. 

Possible ways to address this behavior:
1) Add a `--no-operator` flag to `appsody deploy` that suppresses the installation of the Appsody Operator altogether. The assumption here is that the cluster admin is going to install the operator for the developers.

2) Add a `--no-check` flag to `appsody deploy` and `appsody operator install`, which prevents running the sanity check on the presence of other operators already watching the namespace.  The risk here is that someone might end up with conflicting operators (Appsody would install an operator in the same ns as the app if one isn't there).

**Comment by richard-trotter** [comment]
In my case (and when `--namespace` is specified explicitly), I think `--no-check` would be ok, as I know there will not be another operator watching my namespace. But I also think some better user messages would be a good idea. If I first try without this flag, and the operation fails in this way, then preferably detect that the cause is "not authorized" and explain. Or at least indicate "may be not authorized". Then also recommend using `--no-check` "if you know there is no other operator watching your namespace". Even so, it seems my own namespace should still be checked even if `--no-check` (all namespaces) is in effect.

**Comment by chilanti** [comment]
Agree - we should still avoid attempting to re-deploy the operator if it's already there in the namespace you are targeting.

**Comment by arjunsbabu** [comment]
Hi The --no-check option is not seen in the latest version of appsody. Do i need to build appsody from source for getting the same ?

**Comment by kylegc** [comment]
> Hi The --no-check option is not seen in the latest version of appsody. Do i need to build appsody from source for getting the same ?

No, this issue is still open and under discussion. It has not been implemented yet.

**Comment by chilanti** [comment]
We should also look at adding the flag(s) to `appsody operator install`.
