### ISSUE TITLE
Support the deployment of stacks via configured Operators

### ISSUE THREAD

**Issue by leochr** [appsody/appsody#824]
The first release candidate of Go-based Open Liberty Operator is now available here: https://github.com/OpenLiberty/open-liberty-operator/releases/tag/v0.3.0-rc1

**Request**:
Integrate Open Liberty Operator with Appsody CLI and Stacks related to Open Liberty (i.e. java-microprofile).

- the `app-deploy.yaml` needs to be updated (i.e. use `Kind: OpenLibertyApplication`)
- perhaps `stack.yaml` needs to have a new field which describes the operator it uses (if absent use Appsody Operator)
- Appsody CLI needs to install the Open Liberty operator if not there

**Comment by leochr** [comment]
FYI @neeraj-laad @kylegc @arthurdm @chilanti

**Comment by kylegc** [comment]
@EnriqueL8 Can you investigate the CLI portion of this? In particular, can the CLI handle the OpenLibertyApplication type in the app-deploy.yaml. I'm guessing not, so what needs to be done to support it?

**Comment by EnriqueL8** [comment]
Setting the `kind: OpenLibertyApplication` within the sample `app-deploy.yaml` in the microprofile stack will not get overridden when generating the `app-deploy.yaml` at build, and neither does the `apiVersion` field. This means that if we update the `app-deploy.yaml` in the java-microprofile stack to the OpenLibertyOperator, the generated manifest from the CLI which populates information such as the labels and ports will remain valid. 
Since the OpenLibertyOperator supports all the features of the AppsodyOperator, we can still use the structs from the AppsodyOperator to unmarshall and marshall this manifest. The only limitation would be the features added by the `OpenLibertyOperator` which would get delete by CLI, or the user has the option to modify the manifest directly and use `appsody deploy --no-build`. This raises an issue with dependencies that we want the CLI to have. In order to support all the features of the OpenLiberty CRC, we will need to import the GO structs from the `OpenLibertyOperator` to marshall and unmarshall the manifest. This branches the codebase into very specific use cases, and will need some logic to decide with operator to use such as the suggestion to add a field to the `stack.yaml`. 
But what happens when another operator is created? Are the day 2 features of the `OpenLibertyOperator` specific to `OpenLiberty` or could they be added to the `AppsodyOperator`?

The other issue is installing the operator, do we want to install an operator in a namespace which is only specfic to one stack?

**Comment by leochr** [comment]
> But what happens when another operator is created? Are the day 2 features of the `OpenLibertyOperator` specific to `OpenLiberty` or could they be added to the `AppsodyOperator`?

The CRs for day-2 operations, `OpenLibertyTrace` and `OpenLibertyDump`, are specific to Open Liberty and are only watched by Open Liberty Operator.

**Comment by arthurdm** [comment]
This work is related to this issue: https://github.com/appsody/stacks/issues/601

To support the configuration / usage of other Operators the Appsody CLI needs to be able to tolerate `app-deploy.yaml` with arbitrary `Kind` values.   

Perhaps instead of a schema-based parsing it needs to switch to a model that uses placeholders to insert labels / annotations - which could be required for any given `app-deploy.yaml`.

**Comment by arthurdm** [comment]
thanks for updating the milestone @neeraj-laad 

btw - the adoption of the Open Liberty Operator is targeted for Kabanero 0.7.0, so it would be great if we can line up the Appsody updates with that release.

**Comment by EnriqueL8** [comment]
@arthurdm We have raised a PR #913 to fix this, but we are not installing the Open Liberty Operator as part of this change.

**Comment by arthurdm** [comment]
thanks @EnriqueL8 

It's ok to require the user to install the OL Operator (it's an easy install from OperatorHub).  

Is `stack.yaml` going to be updated to contain an `operator` field that documents which Operator its `app-deploy.yaml` requires?   That way the user knows which one it should ensure is installed.

Which is probably also how the Appsody CLI knows if it should install the Appsody Operator or not? (current behaviour)

**Comment by neeraj-laad** [comment]
@arthurdm We have not added anything to stack.yaml as the developer never gets `stack.yaml` at all. 

Our current implementation will allow a stack creator to configure/bake-in a template deployment manifest in the stack with a `kind` other than Appsody operator.  

Appsody cli will refer to this value and decide if it needs to install the operator or not. 

@EnriqueL8 Do we have logs for the user that indicate that we did not install the operator and that user needs to install it themselves?

**Comment by EnriqueL8** [comment]
Yes, we have added logs for the user.

**Comment by arthurdm** [comment]
thanks for the update @neeraj-laad - this will certainly get us going in the right direction!

Do you guys have a sample of the message the user will see?  My only worry is that if the user sees a message such as "We have not ensured that the Operator watching `Kind: RuntimeComponent` is installed" they will not be able to associate that this means they must install the Application Stacks Operator, for example.  

If we have a field in `stack.yaml` (set by the stack owners like Champ), then that field could contain the Operator name (Application Stacks Operator, Open Liberty Operator, JBoss Operator, etc), which the CLI can print back to the developer, then the developer can easily map to something in OLM they need to install.

**Comment by neeraj-laad** [comment]
@arthurdm The message ewe show today is this: `The deployment manifest is of kind: %s, you need to install a matching operator.`

**Comment by arthurdm** [comment]
Thanks @neeraj-laad - I think we can close this now.  The last piece of work from Appsody will come from https://github.com/appsody/stacks/issues/721

**Comment by EnriqueL8** [comment]
Perfect, closing issue. 
If needed in the future, we can open another issue to support `operator` field in `stack.yaml`.
