### ISSUE TITLE
Stack create test will fail due to latest stack update

### ISSUE THREAD

**Issue by upLukeWeston** [appsody/appsody#890]
**Describe the bug**
When running the unit testing suite on the latest master, the test `TestStackCreateInvalidStackCase2` will fail because of changes made to the `stack create` command.

When running:

```
args := []string{"stack", "create", testStackName, "--copy", "nodejs"}
_, err := cmdtest.RunAppsody(sandbox, args...)

if err == nil {
	t.Fatal(err)
}
```
It will compose a command such as the following :

```
$ appsody stack create test --copy nodejs
Stack created: test
```

However, when I try it with `python-flask`, I get this result:

```
$ appsody stack create test --copy python-flask
[Error] Invalid stack name: python-flask. Stack name must be in the format <repo>/<stack
```
Which is the expected behaviour.

The reason this has made it past Travis into the master is because the Stacks (nodejs, nodejs-express, openliberty and microprofile) were updated this afternoon to now include the `src`, which means they are using the new `stack create` function, rather than the old one (which is still there as a fallback method).

When testing the new `create` function with the testing suite, it would still pull the actual stack from GitHub, which didn't have `src` in them, so this test wouldn't have failed; and manually testing the commands would still work as expected.

Should it be the case that this test is removed from the "invalid" section because the new behaviour of `stack create` expects `appsody stack create test --copy nodejs` to pass, even without the `incubator/nodejs` format? Or should the new `stack create` function maintain this behaviour of expecting the format?

**Comment by EnriqueL8** [comment]
From a quick look, by passing only the stack name `nodejs` the `parseProjectParm`  returns the default repository and in both cases either in the test and locally it contains the stack `nodejs`. What happens when we give it a stack which is not in the default repository? Does it throw an error before reaching the old method? Or does it fail in the oldMethod when it validates the format `repo/stack`?

**Comment by CameronMcWilliam** [comment]
It will fail if not in the default repository.  We need a discussion over what we think the correct design should be.  Imo, this new method is fine as it keeps in line with what the `appsody init` command does.  Even so, these error messages need reworking should be updated to be more useful to developers, this process has been a bit messy than usual due to the fact that we needed two methods in place, phasing one out and implementing the new one.

**Comment by neeraj-laad** [comment]
https://github.com/appsody/appsody/pull/892 PR merged
