### ISSUE TITLE
Quickstart requirements

### ISSUE THREAD

**Issue by rhuss** [appsody/appsody#91]
Following this [blog announcement](https://kabanero.io/blog/2019/07/15/what's-hot-this-week.html) I tried to get my feet wet following the instructions on https://kabanero.io/try-it . Unfortunately, the walkthrough is not very detailed so I tried to reproduce the content of the video.

However, I failed on Minikube for the following reasons:

* `appsody build` runs a multi-stage docker build with volume mounts on the local filesystem to get the source code into the build container. This does not work with remote Docker daemons like Minikube obviously. So I switched to Docker on Mac (as the presenter in the video does as well). With this the build succeeds.
* `appsody deploy` references in the Knative service an image `dev.local/myapp` which has been tagged with this name during the build step. I don't see any push to a registry, so I assume that you have to build against the Docker daemon which is also running Kubernetes, otherwise Kubernetes won't find that image.

This leads me to the conclusion that this workflow only works with Docker Desktop and with the Kubernetes coming with Docker Desktop. And that a local Docker installation is mandatory for using Appsody. 

Is this correct or did I miss something ?

**Comment by chilanti** [comment]
Hi - a few comments:
1) `appsody build` requires a "local" Docker daemon.  It can be made to work in a docker-in-docker situation, as we do in our [Tekton example](https://github.com/appsody/tekton-example). Not straightforward, but possible.
2) `appsody build` has been enhanced in version 0.2.5 to support `-t <tag>` - so that you can tag your image as you wish.
3) `appsody deploy` has always supported `-t <tag> --push`. If you use those flags, during `deploy` we'll tag the image and push it to whatever Docker registry your user has logged into (we issue plain `docker` commands). The Knative serving yaml manifest will then reflect that image tagging and will be pushed to any K8S cluster your local `kubectl` CLI is associated with.

Let me know if this helps or if there are further questions - thanks!

**Comment by chilanti** [comment]
Forgot: we recently update the Appsody docs for `build` and `deploy` to address some of your questions: https://appsody.dev/docs/using-appsody/building-and-deploying.

**Comment by rhuss** [comment]
@chilanti thanks for the super fast response !

> 1. It can also work in a docker-in-docker situation, as we do in our [Tekton example](https://github.com/appsody/tekton-example). Not straightforward, but possible.

It's probably not possible everywhere and many clusters have issues with dind setups. Are there any plans to get the source differently into the cluster for building ? How would you run appsody with minikube (which is effectively a remode Docker daemon) ?

> 3\. The Knative serving yaml manifest will then reflect that image tagging and will be pushed to any K8S cluster your local `kubectl` CLI is associated with.

Cool. So when I understand correctly, a local Docker installation is always mandatory.

I'm a bit unsure about the Developer workflow (sorry, haven't yet read the Tekton example). I as "Jane" from Kabanero, do I need a Docker setup which supports volume mounts to my local directories on my machine ?

Thanks for the pointers. 'will catch up now ;-). Nice weekend ...

**Comment by chilanti** [comment]
@rhuss - back to this one... yes, we are working to restructure the Tekton pipeline to use `buildah` instead of d-in-d. Timeline still uncertain. Currently, the only plan to have an Appsody build occur in K8S is by means of a Tekton pipeline (i.e. no plans yet for an Openshift build for example). 
To your second question, yes, a local Docker daemon is a requirement for Jane, and yes, that Docker daemon needs to be able to mount local dirs.

The idea of the overall flow is:

1. Jane develops locally
1. Jane unit tests locally, on a local Docker daemon
1. Jane can also build and deploy her image on a local K8S cluster (or build locally and deploy to a cluster she has access to, as long as that has Knative installed).
1. When she's done, Jane checks all her code into GitHub.
1. A PR or a push will trigger a Tekton pipeline execution via an adequately configured webhook
1. The pipeline builds the image again and deploys it.

As you can imagine, it's unlikely that the deployment manifest is the one that Jane checks into GitHub, in "real life". I would expect the ops team to define the config/deploy manifests (perhaps in a different repo altogether). But for sake of simplicity, the example we have for Tekton assumes that Jane checks in the manifest...

**Comment by neeraj-laad** [comment]
Closing this issue as it appears to be a discussion to understand the requirements for current appsody to work. Especially around deployments. 

Please feel free to re-open and clearly state the issue/enhancement you have in mind.
