### ISSUE TITLE
operator install to developer project (namespace) on CRC cluster fails with "forbidden"

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody#920]
@richard-trotter commented on [Thu Feb 20 2020](https://github.com/appsody/appsody-operator/issues/221)

### What did you do?
I am trying to install the operator to a local CRC cluster. I've created a project.
```
% odo project list
ACTIVE     NAME
*          odo-one
```
And then I run:
`appsody operator install -n odo-one --no-operator-check
`
And I get an error reported to console.
```
customresourcedefinitions.apiextensions.k8s.io "appsodyapplications.appsody.dev" is forbidden: 
User "developer" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

### What did you expect to see?

Expected the operator to install to the specified namespace.

### What did you see instead?

as shown above

### Environment

Using appsody v0.5.8.
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)

**Comment by brightzheng100** [comment]
It happened to my OCP v4.2 env as well.

I was using a non-admin user so it failed.
After granting the admin role, there is still an issue for creating the appsody operator pod.

This was the process:

```
$ oc version
Client Version: openshift-clients-4.2.0-201910041700
Server Version: 4.2.16
Kubernetes Version: v1.14.6+8bbaf43

$ appsody operator install -n bright-project -w bright-project
$ kg deploy,svc,rs,po -n bright-project
NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/appsody-operator   0/1     0            0           12m
NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.extensions/appsody-operator-988455d4f   1         0         0       12m

$ kg replicaset.extensions/appsody-operator-988455d4f -o yaml
...
status:
  conditions:
  - lastTransitionTime: "2020-02-28T16:03:23Z"
    message: 'pods "appsody-operator-988455d4f-" is forbidden: unable to validate
      against any security context constraint: []'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```

The lazy workaround I did was, to me:

```
$ oc adm policy add-scc-to-user privileged -z appsody-operator
```

Interestingly, from the files under `~/.appsody/deploy/`, I couldn't see any specific security contexts required but it turns out it still complains about that.

So what permission it really needs to run the Appsody Operator?

**Comment by Kamran64** [comment]
I think this a more a problem with permissions in the cluster rather than a bug in Appsody. I recreated this using CRC but only when running as a non admin user. However, I do think that we should improve our documentation to state what permissions are required to install the operator. And possibly improve the help text for the `no-operator-check` flag.

That flag is used only when the user doesn't have the permissions in a cluster to run a `kubectl get pods --all-namespaces` which we run when determining where the operator has already been installed.
