### ISSUE TITLE
Ability to perform appsody init in a k8s pod where docker is missing

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/appsody#933]
We need to enable `appsody init` from within a container running on Kubernetes, where there is no docker available.

We might need to consider what steps can be performed in such a case:

- Create a template project
- Create the project configuration file
- Execute init hook (if stack needs other setups)
- Validate requirements for the stack are met

**Comment by Kamran64** [comment]
We have options for users who want to run Appsody without Docker. For example, the `APPSODY_K8S_EXPERIMENTAL` environment variable uses Buildah to pull images during the `init` phase instead of Docker (and also handles running the init scripts). The requirements checker shouldn't be a problem either as it will skip the Docker prereq check if Buildah is being used.

For ease of convenience we also have an [appsody-kube](https://github.com/appsody/appsody-kube) repo which bundles the Appsody CLI, Buildah, and kubectl into an image which covers the requirements for this issue.

However we should be better documenting these tools (maybe on the website) and possibly releasing `appsody-kube` during each CLI release.

**Comment by neeraj-laad** [comment]
@seabaylea

**Comment by Kamran64** [comment]
Closing this issue, adding docs for this will be tracked in https://github.com/appsody/website/issues/539
